### ISSUE TITLE
[Feature Request]: Use old menus when not using hw rendering

### ISSUE THREAD

**Issue by JeodC** [RSDKModding/RSDKv4-Decompilation#438]
### Before opening this issue, I ensure that...

- [X] I have read the [FAQ](https://github.com/RSDKModding/RSDKv4-Decompilation/blob/main/FAQ.md) and confirmed my issue is not mentioned in it.
- [X] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [X] I am not asking for tech support (e.g. game closing on startup, error when trying to build, etc).
- [X] I am not asking for modding support or reporting a bug in a specific mod; this bug either occurs without mods enabled or is directly related to the mod loader.
- [X] This bug is not related to any unofficial fork/port of the decompilation, and any issues with those should be kept in the appropriate repository.

### Expected Behavior

Not a bug

### Actual Behavior

Not a bug

### Steps to Reproduce

Not a bug

### Screenshots

![image](https://github.com/user-attachments/assets/54266de7-0c7a-4df4-8cdc-f046ee486a5a)

### Decompilation Version

8de9266c7130b1f40e8736dbd4aeec322c77c7ea

### Game

Sonic 1

### Game Version

Mobile (Sega Forever)

### Platform

aarch64

### Additional Comments

Built with flags `-DRETRO_SDL_VERSION=2 -DRETRO_USE_HW_RENDER=OFF` for use with embedded systems. Had a user ask about the old style menus, since the new ones rely on HW_RENDER and I didn't use that due to performance issues. This is a feature request to fallback to the old style pause menu if not using HW_RENDER.

Related to #418

Thank you.

**Comment by MegAmi24** [comment]
The old menus will not be added back as they were simply placeholders for the HW menu, with no alternatives available at the time. Nowadays, mods such as [Menu Recreation](https://gamebanana.com/mods/316733) exist that can be used in its place for no-OGL builds (this mod works with both S1 and S2).

Also, we only accept issues for bug reports. Please do not make feature requests.
